# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-11 07:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Код')),
                ('customername', models.CharField(max_length=256, verbose_name='Имя')),
                ('extattrvalue', models.CharField(max_length=256, verbose_name='Данные')),
                ('status', models.IntegerField(verbose_name='Статус')),
            ],
            options={
                'db_table': 'tbl_customer',
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='customerattribute',
            fields=[
                ('attr_id', models.AutoField(primary_key=True, serialize=False)),
                ('attr_name', models.CharField(max_length=256, verbose_name='Наименование')),
                ('attr_desc', models.CharField(max_length=256, verbose_name='Описание')),
                ('attr_type', models.IntegerField(verbose_name='Тип')),
                ('attr_mask', models.CharField(max_length=50, verbose_name='Маска')),
                ('attr_nullable', models.IntegerField(verbose_name='Обязательность заполнения')),
                ('status', models.IntegerField(verbose_name='Статус')),
            ],
            options={
                'db_table': 'tbl_customerattribute',
                'verbose_name': 'Атрибуты клиента',
                'verbose_name_plural': 'Атрибуты клиентов',
            },
        ),
        migrations.CreateModel(
            name='customerattrval',
            fields=[
                ('extattr', models.AutoField(primary_key=True, serialize=False)),
                ('cliattr_value', models.CharField(max_length=256, verbose_name='Значение')),
                ('cliattr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customerattribute')),
                ('customer', models.ManyToManyField(to='customer.customer')),
            ],
            options={
                'db_table': 'tbl_customerattrval',
                'verbose_name': 'Значения атрибутов клиента',
                'verbose_name_plural': 'Значения атрибутов клиентов',
            },
        ),
        migrations.CreateModel(
            name='customertype',
            fields=[
                ('customertype_id', models.AutoField(primary_key=True, serialize=False)),
                ('customertypename', models.CharField(max_length=256, verbose_name='Наименование')),
            ],
            options={
                'db_table': 'tbl_customertype',
                'verbose_name': 'Тип клиента',
                'verbose_name_plural': 'Типы клиентов',
            },
        ),
        migrations.CreateModel(
            name='owner',
            fields=[
                ('owner_id', models.AutoField(primary_key=True, serialize=False)),
                ('ownername', models.CharField(max_length=256, verbose_name='Наименование')),
                ('ownertype', models.IntegerField()),
                ('owner_address_jur', models.CharField(max_length=256, verbose_name='Юридический адрес')),
                ('owner_address_post', models.CharField(max_length=256, verbose_name='Почтовый адрес')),
                ('owner_ogrn', models.CharField(max_length=13, verbose_name='ОГРН')),
                ('owner_inn', models.CharField(max_length=12, verbose_name='ИНН')),
                ('owner_kpp', models.CharField(max_length=9, verbose_name='КПП')),
                ('owner_account', models.CharField(max_length=20, verbose_name='Расчетный счет')),
            ],
            options={
                'db_table': 'tbl_owner',
                'verbose_name': 'Контрагент',
                'verbose_name_plural': 'Контрагенты',
            },
        ),
        migrations.AddField(
            model_name='customertype',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.owner'),
        ),
        migrations.AddField(
            model_name='customerattribute',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.owner'),
        ),
        migrations.AddField(
            model_name='customer',
            name='customertype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customertype'),
        ),
        migrations.AddField(
            model_name='customer',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.owner'),
        ),
    ]
