# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-11 07:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customertype',
            name='owner',
        ),
        migrations.AlterField(
            model_name='owner',
            name='ownertype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customertype'),
        ),
    ]
