# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-11 07:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20160311_1004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerattrval',
            name='customer',
        ),
        migrations.AddField(
            model_name='customerattrval',
            name='customer',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='customer.customer'),
            preserve_default=False,
        ),
    ]
