# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-14 14:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20160311_1017'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerShablon',
            fields=[
                ('CustomerShablon_id', models.AutoField(primary_key=True, serialize=False)),
                ('CustomerShablon_Name', models.CharField(max_length=256, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Шаблон клиента',
                'verbose_name_plural': 'Шаблоны клиентов',
                'db_table': 'tbl_customershablon',
            },
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='customername',
            new_name='customer_name',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='extattrvalue',
            new_name='ext_attr_value',
        ),
        migrations.RenameField(
            model_name='customerattrval',
            old_name='cliattr_value',
            new_name='cli_attr_value',
        ),
        migrations.RenameField(
            model_name='customerattrval',
            old_name='extattr',
            new_name='ext_attr',
        ),
        migrations.RenameField(
            model_name='customertype',
            old_name='customertypename',
            new_name='customertype_name',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='ownername',
            new_name='owner_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='customertype',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='customerattribute',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='customerattrval',
            name='cliattr',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='ownertype',
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='customer.CustomerType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerattrval',
            name='cli_attr',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='customer.CustomerAttribute'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='owner',
            name='owner_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='customer.CustomerType'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customerattrval',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer'),
        ),
        migrations.AddField(
            model_name='customershablon',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Owner'),
        ),
        migrations.AddField(
            model_name='customer',
            name='customershablon',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='customer.CustomerShablon'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerattribute',
            name='customershablon',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='customer.CustomerShablon'),
            preserve_default=False,
        ),
    ]
