# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-15 12:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_auto_20160314_1807'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldType',
            fields=[
                ('fieldtype_id', models.AutoField(primary_key=True, serialize=False)),
                ('fieldtype_name', models.CharField(max_length=256, verbose_name='Наименование')),
                ('fieldtype_descr', models.CharField(max_length=256, verbose_name='Описание')),
            ],
            options={
                'verbose_name_plural': '01 Типы полей',
                'verbose_name': 'Тип поля',
                'db_table': 'tbl_fieldtype',
            },
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': '05 Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='customerattribute',
            options={'verbose_name': 'Атрибуты клиента', 'verbose_name_plural': '04 Атрибуты клиентов'},
        ),
        migrations.AlterModelOptions(
            name='customerattrval',
            options={'verbose_name': 'Значения атрибутов клиента', 'verbose_name_plural': '06 Значения атрибутов клиентов'},
        ),
        migrations.AlterModelOptions(
            name='customershablon',
            options={'verbose_name': 'Шаблон клиента', 'verbose_name_plural': '03 Шаблоны клиентов'},
        ),
        migrations.AlterModelOptions(
            name='customertype',
            options={'verbose_name': 'Тип клиента', 'verbose_name_plural': '01 Типы клиентов'},
        ),
        migrations.AlterModelOptions(
            name='owner',
            options={'verbose_name': 'Контрагент', 'verbose_name_plural': '02 Контрагенты'},
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.CustomerType'),
        ),
        migrations.AlterField(
            model_name='customerattribute',
            name='attr_desc',
            field=models.CharField(max_length=256, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='customerattribute',
            name='attr_mask',
            field=models.CharField(max_length=50, null=True, verbose_name='Маска'),
        ),
        migrations.AlterField(
            model_name='customerattribute',
            name='attr_nullable',
            field=models.IntegerField(choices=[(1, 'Да'), (2, 'Нет')], default=2, verbose_name='Обязательность заполнения'),
        ),
        migrations.AlterField(
            model_name='customerattribute',
            name='attr_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.FieldType'),
        ),
        migrations.AlterField(
            model_name='customerattrval',
            name='cli_attr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.CustomerAttribute'),
        ),
        migrations.AlterField(
            model_name='customerattrval',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer'),
        ),
        migrations.AlterField(
            model_name='customershablon',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Owner'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='owner_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.CustomerType'),
        ),
    ]
