# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-15 12:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0013_auto_20160315_1527'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': '06 Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='customerattribute',
            options={'verbose_name': 'Атрибуты клиента', 'verbose_name_plural': '05 Атрибуты клиентов'},
        ),
        migrations.AlterModelOptions(
            name='customerattrval',
            options={'verbose_name': 'Значения атрибутов клиента', 'verbose_name_plural': '07 Значения атрибутов клиентов'},
        ),
        migrations.AlterModelOptions(
            name='customershablon',
            options={'verbose_name': 'Шаблон клиента', 'verbose_name_plural': '04 Шаблоны клиентов'},
        ),
        migrations.AlterModelOptions(
            name='owner',
            options={'verbose_name': 'Контрагент', 'verbose_name_plural': '03 Контрагенты'},
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.CustomerType'),
        ),
        migrations.AlterField(
            model_name='customerattribute',
            name='attr_desc',
            field=models.CharField(blank=True, default=None, max_length=256, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customerattribute',
            name='attr_mask',
            field=models.CharField(blank=True, default=None, max_length=50, verbose_name='Маска'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customerattrval',
            name='cli_attr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.CustomerAttribute'),
        ),
        migrations.AlterField(
            model_name='customerattrval',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer'),
        ),
        migrations.AlterField(
            model_name='customershablon',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Owner'),
        ),
        migrations.AlterField(
            model_name='fieldtype',
            name='fieldtype_descr',
            field=models.CharField(blank=True, max_length=256, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='owner_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.CustomerType'),
        ),
    ]
