# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 13:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('ItemId', models.AutoField(primary_key=True, serialize=False)),
                ('ItemName', models.CharField(max_length=50, verbose_name='Наименование элемента меню')),
                ('ItemShowName', models.CharField(default='', max_length=50, verbose_name='Отображаемое имя')),
                ('ItemClick', models.CharField(max_length=100, verbose_name='Событие по клику')),
                ('ItemIsActive', models.IntegerField(default=0, verbose_name='Признак активности')),
                ('ItemOrder', models.IntegerField(default=0, verbose_name='Порядок группировки')),
            ],
        ),
        migrations.CreateModel(
            name='MenuItemType',
            fields=[
                ('ItemTypeId', models.AutoField(primary_key=True, serialize=False)),
                ('ItemTypeName', models.CharField(max_length=50, verbose_name='Тип элемента меню')),
                ('ItemTypeShowName', models.CharField(default='', max_length=50, verbose_name='Отображаемое имя')),
            ],
        ),
        migrations.CreateModel(
            name='MenuSubItem',
            fields=[
                ('SubItemId', models.AutoField(primary_key=True, serialize=False)),
                ('SubItemName', models.CharField(max_length=50, verbose_name='Наименование подэлемента меню')),
                ('SubItemClick', models.CharField(max_length=100, verbose_name='Событие по клику')),
                ('SubItemOrder', models.IntegerField(default=0, verbose_name='Порядок группировки')),
                ('ParentMenu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.MenuItem')),
            ],
        ),
        migrations.AddField(
            model_name='menuitem',
            name='ItemType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.MenuItemType'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='ParentMenu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ChildMenu', to='menu.MenuItem'),
        ),
    ]
